In [4]:
from google.colab import drive

# Monta o Drive
drive.mount('/content/drive')

# Carrega o dataset
iris_path = '/content/drive/MyDrive/DATA_ANALITYCs/AULA_09/IRIS/iris.csv'


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [5]:
# Importando as bibliotecas necessárias
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Carregando o conjunto de dados Iris
iris = load_iris()
X = iris.data  # Atributos (comprimento/largura de sépala/pétala)
y = iris.target  # Variável dependente (espécie)

# Dividindo os dados em conjuntos de treino e teste (75% treino, 25% teste)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=123)

# Criando e treinando o modelo de Regressão Logística
model = LogisticRegression(random_state=123, max_iter=1000)
model.fit(X_train, y_train)

# Fazendo previsões no conjunto de teste
y_pred = model.predict(X_test)

# Calculando a acurácia do modelo
accuracy = accuracy_score(y_test, y_pred)

# Obtendo os coeficientes e o viés (intercept)
coefficients = model.coef_
intercept = model.intercept_

# Exibindo os resultados
print("Resultados do Modelo de Classificação para o Dataset Iris")
print("------------------------------------------------------")
print(f"Acurácia do modelo nos dados de teste: {accuracy:.4f} ({accuracy*100:.2f}%)")
print("\nCoeficientes dos atributos:")
print("(Cada linha representa uma classe, cada coluna um atributo na ordem: sepal length, sepal width, petal length, petal width)")
print(coefficients)
print("\nViés (intercept) para cada classe:")
print(intercept)

Resultados do Modelo de Classificação para o Dataset Iris
------------------------------------------------------
Acurácia do modelo nos dados de teste: 0.9737 (97.37%)

Coeficientes dos atributos:
(Cada linha representa uma classe, cada coluna um atributo na ordem: sepal length, sepal width, petal length, petal width)
[[-0.44761018  0.86792964 -2.35836563 -0.98974545]
 [ 0.51526119 -0.24634842 -0.18000152 -0.87022083]
 [-0.06765102 -0.62158121  2.53836715  1.85996628]]

Viés (intercept) para cada classe:
[  9.58860033   1.87493505 -11.46353538]


In [8]:
from sklearn.datasets import load_iris

iris = load_iris()
X = iris['data']
y = iris['target']

print('Nomes dos Atributos: ', iris['feature_names'], '\n')
print('Tamanho de X: ', X.shape, '\n')
print('Tamanho de y: ', y.shape, '\n')

Nomes dos Atributos:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)'] 

Tamanho de X:  (150, 4) 

Tamanho de y:  (150,) 



In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=123)
print('Tamanho de X_train: ', X_train.shape, '\n')
print('Tamanho de X_test: ', X_test.shape, '\n')
print('Tamanho de y_train: ', y_train.shape, '\n')
print('Tamanho de y_test: ', y_test.shape, '\n')
from sklearn.linear_model import LogisticRegression

Tamanho de X_train:  (112, 4) 

Tamanho de X_test:  (38, 4) 

Tamanho de y_train:  (112,) 

Tamanho de y_test:  (38,) 

